In [1]:
import pandas as pd
import numpy as np
import warnings 
warnings.filterwarnings('ignore')

In [2]:
dataset=pd.read_csv('movies_metadata.csv')
dataset

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45461,False,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 10751, 'n...",http://www.imdb.com/title/tt6209470/,439050,tt6209470,fa,رگ خواب,Rising and falling between a man and woman.,...,NaN,0.0,90.0,"[{'iso_639_1': 'fa', 'name': 'فارسی'}]",Released,Rising and falling between a man and woman,Subdue,False,4.0,1.0
45462,False,NaN,0,"[{'id': 18, 'name': 'Drama'}]",NaN,111109,tt2028550,tl,Siglo ng Pagluluwal,An artist struggles to finish his work while a...,...,2011-11-17,0.0,360.0,"[{'iso_639_1': 'tl', 'name': ''}]",Released,NaN,Century of Birthing,False,9.0,3.0
45463,False,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",NaN,67758,tt0303758,en,Betrayal,"When one of her hits goes wrong, a professiona...",...,2003-08-01,0.0,90.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,A deadly game of wits.,Betrayal,False,3.8,6.0
45464,False,NaN,0,[],NaN,227506,tt0008536,en,Satana likuyushchiy,"In a small town live two brothers, one a minis...",...,1917-10-21,0.0,87.0,[],Released,NaN,Satan Triumphant,False,0.0,0.0
45465,False,NaN,0,[],NaN,461257,tt6980792,en,Queerama,50 years after decriminalisation of homosexual...,...,2017-06-09,0.0,75.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Queerama,False,0.0,0.0

In [3]:
dataset.isnull().sum()

adult                        0
belongs_to_collection    40972
budget                       0
genres                       0
homepage                 37684
id                           0
imdb_id                     17
original_language           11
original_title               0
overview                   954
popularity                   5
poster_path                386
production_companies         3
production_countries         3
release_date                87
revenue                      6
runtime                    263
spoken_languages             6
status                      87
tagline                  25054
title                        6
video                        6
vote_average                 6
vote_count                   6
dtype: int64

In [4]:
dataset.title.unique()

array(['Toy Story', 'Jumanji', 'Grumpier Old Men', ...,
       'Century of Birthing', 'Satan Triumphant', 'Queerama'],
      dtype=object)

In [5]:
len(dataset.title.unique())

42278

In [6]:
dataset.title.value_counts()

title
Cinderella              11
Hamlet                   9
Alice in Wonderland      9
Beauty and the Beast     8
Les Misérables           8
                        ..
Cluny Brown              1
Babies                   1
The Green Room           1
Captain Conan            1
Queerama                 1
Name: count, Length: 42277, dtype: int64

In [7]:
dataset = dataset[dataset['original_language'] == 'en']

In [8]:
import ast

def clean_genres(text):
    genres = []
    
    try:
        text = ast.literal_eval(text)
        
        for item in text:
            genres.append(item['name'])
            
        return " ".join(genres)
    
    except:
        return ""

In [9]:
dataset['genres'] = dataset['genres'].apply(clean_genres)
dataset['genres']

0         Animation Comedy Family
1        Adventure Fantasy Family
2                  Romance Comedy
3            Comedy Drama Romance
4                          Comedy
                   ...
45459             Science Fiction
45460        Drama Action Romance
45463       Action Drama Thriller
45464
45465
Name: genres, Length: 32269, dtype: object

In [10]:
dataset.rename(columns={'original_title':'Title'},inplace=True)
dataset

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,Title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,Animation Comedy Family,http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,Adventure Fantasy Family,NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,Romance Comedy,NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,Comedy Drama Romance,NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,Comedy,NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45459,False,NaN,0,Science Fiction,NaN,222848,tt0112613,en,Caged Heat 3000,It's the year 3000 AD. The world's most danger...,...,1995-01-01,0.0,85.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Caged Heat 3000,False,3.5,1.0
45460,False,NaN,0,Drama Action Romance,NaN,30840,tt0102797,en,Robin Hood,"Yet another version of the classic epic, with ...",...,1991-05-13,0.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Robin Hood,False,5.7,26.0
45463,False,NaN,0,Action Drama Thriller,NaN,67758,tt0303758,en,Betrayal,"When one of her hits goes wrong, a professiona...",...,2003-08-01,0.0,90.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,A deadly game of wits.,Betrayal,False,3.8,6.0
45464,False,NaN,0,,NaN,227506,tt0008536,en,Satana likuyushchiy,"In a small town live two brothers, one a minis...",...,1917-10-21,0.0,87.0,[],Released,NaN,Satan Triumphant,False,0.0,0.0
45465,False,NaN,0,,NaN,461257,tt6980792,en,Queerama,50 years after decriminalisation of homosexual...,...,2017-06-09,0.0,75.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Queerama,False,0.0,0.0

In [11]:
dataset=dataset[['Title','genres']]
dataset

                             Title                    genres
0                        Toy Story   Animation Comedy Family
1                          Jumanji  Adventure Fantasy Family
2                 Grumpier Old Men            Romance Comedy
3                Waiting to Exhale      Comedy Drama Romance
4      Father of the Bride Part II                    Comedy
...                            ...                       ...
45459              Caged Heat 3000           Science Fiction
45460                   Robin Hood      Drama Action Romance
45463                     Betrayal     Action Drama Thriller
45464          Satana likuyushchiy
45465                     Queerama

[32269 rows x 2 columns]

In [12]:
dataset.genres

0         Animation Comedy Family
1        Adventure Fantasy Family
2                  Romance Comedy
3            Comedy Drama Romance
4                          Comedy
                   ...
45459             Science Fiction
45460        Drama Action Romance
45463       Action Drama Thriller
45464
45465
Name: genres, Length: 32269, dtype: object

In [13]:
dataset.isnull().sum()

Title     0
genres    0
dtype: int64

In [14]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [15]:
tfi=TfidfVectorizer(stop_words='english')
tfi_vector=tfi.fit_transform(dataset['genres'])
tfi_vector

<32269x22 sparse matrix of type '<class 'numpy.float64'>'
	with 69147 stored elements in Compressed Sparse Row format>

In [16]:
tfi_vector.shape

(32269, 22)

In [17]:
tfi_vector.toarray()

array([[0.        , 0.        , 0.70430341, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.54093917, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.66449169, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [18]:
from sklearn.metrics.pairwise import cosine_similarity

In [19]:
similar=cosine_similarity(tfi_vector)

In [20]:
df=pd.DataFrame(similar,columns=dataset.Title,index=dataset.Title)
df

Title,Toy Story,Jumanji,Grumpier Old Men,Waiting to Exhale,Father of the Bride Part II,Heat,Sabrina,Tom and Huck,Sudden Death,GoldenEye,...,Deep Hearts,The Morning After,House of Horrors,Shadow of the Blair Witch,The Burkittsville 7,Caged Heat 3000,Robin Hood,Betrayal,Satana likuyushchiy,Queerama
Title,,,,,,,,,,,,,,,,,,,,,
Toy Story,1.000000,0.342625,0.227153,0.201882,0.371433,0.000000,0.227153,0.360284,0.000000,0.000000,...,0.0,0.283934,0.00000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0
Jumanji,0.342625,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.644977,0.357246,0.357246,...,0.0,0.000000,0.00000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0
Grumpier Old Men,0.227153,0.000000,1.000000,0.888747,0.611559,0.000000,1.000000,0.000000,0.000000,0.000000,...,0.0,0.467493,0.00000,0.0,0.0,0.0,0.506720,0.000000,0.0,0.0
Waiting to Exhale,0.201882,0.000000,0.888747,1.000000,0.543521,0.157325,0.888747,0.141358,0.000000,0.000000,...,0.0,0.711017,0.00000,0.0,0.0,0.0,0.641730,0.197288,0.0,0.0
Father of the Bride Part II,0.371433,0.000000,0.611559,0.543521,1.000000,0.000000,0.611559,0.000000,0.000000,0.000000,...,0.0,0.764429,0.00000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Caged Heat 3000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.000000,0.00000,0.0,0.0,1.0,0.000000,0.000000,0.0,0.0
Robin Hood,0.000000,0.000000,0.506720,0.641730,0.000000,0.484862,0.506720,0.435654,0.356327,0.356327,...,0.0,0.269169,0.00000,0.0,0.0,0.0,1.000000,0.608024,0.0,0.0
Betrayal,0.000000,0.000000,0.000000,0.197288,0.000000,0.797439,0.000000,0.449093,0.677795,0.677795,...,0.0,0.277473,0.29138,0.0,0.0,0.0,0.608024,1.000000,0.0,0.0
Satana likuyushchiy,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.000000,0.00000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0
Queerama,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.000000,0.00000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0

In [21]:
df.columns.name=None

In [22]:
df.index.name=None

In [23]:
df

,Toy Story,Jumanji,Grumpier Old Men,Waiting to Exhale,Father of the Bride Part II,Heat,Sabrina,Tom and Huck,Sudden Death,GoldenEye,...,Deep Hearts,The Morning After,House of Horrors,Shadow of the Blair Witch,The Burkittsville 7,Caged Heat 3000,Robin Hood,Betrayal,Satana likuyushchiy,Queerama
Toy Story,1.000000,0.342625,0.227153,0.201882,0.371433,0.000000,0.227153,0.360284,0.000000,0.000000,...,0.0,0.283934,0.00000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0
Jumanji,0.342625,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.644977,0.357246,0.357246,...,0.0,0.000000,0.00000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0
Grumpier Old Men,0.227153,0.000000,1.000000,0.888747,0.611559,0.000000,1.000000,0.000000,0.000000,0.000000,...,0.0,0.467493,0.00000,0.0,0.0,0.0,0.506720,0.000000,0.0,0.0
Waiting to Exhale,0.201882,0.000000,0.888747,1.000000,0.543521,0.157325,0.888747,0.141358,0.000000,0.000000,...,0.0,0.711017,0.00000,0.0,0.0,0.0,0.641730,0.197288,0.0,0.0
Father of the Bride Part II,0.371433,0.000000,0.611559,0.543521,1.000000,0.000000,0.611559,0.000000,0.000000,0.000000,...,0.0,0.764429,0.00000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Caged Heat 3000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.000000,0.00000,0.0,0.0,1.0,0.000000,0.000000,0.0,0.0
Robin Hood,0.000000,0.000000,0.506720,0.641730,0.000000,0.484862,0.506720,0.435654,0.356327,0.356327,...,0.0,0.269169,0.00000,0.0,0.0,0.0,1.000000,0.608024,0.0,0.0
Betrayal,0.000000,0.000000,0.000000,0.197288,0.000000,0.797439,0.000000,0.449093,0.677795,0.677795,...,0.0,0.277473,0.29138,0.0,0.0,0.0,0.608024,1.000000,0.0,0.0
Satana likuyushchiy,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.000000,0.00000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0
Queerama,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.000000,0.00000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0

In [24]:
df.columns

Index(['Toy Story', 'Jumanji', 'Grumpier Old Men', 'Waiting to Exhale',
       'Father of the Bride Part II', 'Heat', 'Sabrina', 'Tom and Huck',
       'Sudden Death', 'GoldenEye',
       ...
       'Deep Hearts', 'The Morning After', 'House of Horrors',
       'Shadow of the Blair Witch', 'The Burkittsville 7', 'Caged Heat 3000',
       'Robin Hood', 'Betrayal', 'Satana likuyushchiy', 'Queerama'],
      dtype='object', length=32269)

In [25]:
def movie_recommendation(movie_name,top_rec):
    if movie_name not in df.index:
        return f"{movie_name} not found in the dataset"
    similarity=df[movie_name].sort_values(ascending=False)
    result=similarity.iloc[1:top_rec+1]
    result=round(result,2)*100
    return result.to_frame("Similarity")

In [26]:
movie_recommendation('Father of the Bride Part II',5)

                             Similarity
The Vagabond                      100.0
Blondie Has Servant Trouble       100.0
Campus Man                        100.0
Jim Jefferies: Contraband         100.0
Bo Burnham: what.                 100.0